service: prime-generator

custom:
  namespace: prime-generator-${self:custom.stage}
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: dev
  environment:
    PRIMES_TABLE: ${self:custom.namespace}-primes
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:*:*:table/${self:provider.environment.PRIMES_TABLE}

functions:
  findPrime:
    handler: handler.findPrime
    events:
      - schedule:
          rate: rate(60 minutes)
          enabled: true

resources:
  Resources:
    PrimeNumberTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.PRIMES_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
