version: 2
updates:
- package-ecosystem: npm
  directory: "/viewer"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - akhtarja
  assignees:
  - akhtarja
- package-ecosystem: npm
  directory: "/generator"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - akhtarja
  assignees:
  - akhtarja
- package-ecosystem: npm
  directory: "/app"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - akhtarja
  assignees:
  - akhtarja
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  reviewers:
  - akhtarja
  assignees:
  - akhtarja
