version: 1
update_configs:
- package_manager: "javascript"
  directory: "/"
  update_schedule: "daily"
  default_reviewers:
    - "akhtarja"
- package_manager: "javascript"
  directory: "/app"
  update_schedule: "daily"
  default_reviewers:
    - "akhtarja"
- package_manager: "javascript"
  directory: "/generator"
  update_schedule: "daily"
  default_reviewers:
    - "akhtarja"
- package_manager: "javascript"
  directory: "/viewer"
  update_schedule: "daily"
  default_reviewers:
    - "akhtarja"